### PR TITLE
Update android data

### PR DESCRIPTION
**Pull request by Holi0317**
Because of issue #1138, I tried to update UA of yowsup (android only. Does not fix the issue as Yowsup is using Nokia UA by default)

I just calculated this by using mgp25/classesMD5-64. But I am not sure if this is valid (I don't have a unused number on me)

### CODE REVIEW

**Comment by mgp25** [comment]
@Holi0317 its correct :+1: but i recommend using Nokia data instead.

Regards

**Comment by Holi0317** [comment]
Is there any difference between Android and Nokia one?

**Comment by mgp25** [comment]
@Holi0317 yes. Android is the most updated platform which means all new features arrive first in Android, so sometimes the API wont work perfectly. Nokia instead gets updated once every one or two months or more, so its easier to control and make thinks better. (it also supports end to end encryption)

**Comment by Holi0317** [comment]
Thanks. Didn't know about that ;)

**Pull request merged**
