### PR TITLE
Updated S40 env to 2.16.11

### LINKED ISSUE #1885: Registration: {"status":"fail","reason":"old_version"}
Can not register. Please help. 
Tried to change values to
```
2.16.11
PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}
```

Don't work.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes #1885.

### CODE REVIEW

**Comment by iice** [comment]
👍

**Comment by mattijsf** [comment]
I'd love to see this PR merged. Yowsup seems currently unusable due to this outdated version error.

**Comment by Jan2220** [comment]
after changing, same error:
status: fail
reason: bad_token
login: MY_PHONENUMBER

:/

**Comment by handflucht** [comment]
works for me.
@Mailaender can you please provide some information, what are the necessary steps to get the two values (version and token)?
I think this would help a lot if it breaks again.

**Comment by Mailaender** [comment]
You need to ask @sebastianancho who provided those values in https://github.com/tgalal/yowsup/issues/1885#issuecomment-269139157.

**Pull request merged**
