### PR TITLE
Media Client

### PR DESCRIPTION
**Pull request by douglasfsti**
A simple implementation of media client.

### CODE REVIEW

**Comment by tgalal** [comment]
Thanks a for the request. Is the addition of the extra dependency 'python-magic' necessary? I see it was only used for guessing getting mimetype, but we can also use mimetypes standard module for this, right?

**Comment by douglasfsti** [comment]
Yes of course, but, I had some troubles with mimetypes standard module, it always return one tuple (None, None) in files without extension.

```
In [1]: import mimetypes

In [2]: mimetypes.guess_type('folder.jpeg')
Out[2]: ('image/jpeg', None)

In [3]: mimetypes.guess_type('folder')
Out[3]: (None, None)


In [1]: import magic

In [2]: magic.from_file('folder.jpeg', mime=True)
Out[2]: 'image/jpeg'

In [3]: magic.from_file('folder', mime=True)
Out[3]: 'image/jpeg'
```

**Comment by stogg** [comment]
Hi! im trying your code, but sending stuck at last point there:
self._sendIq(entity, successFn, errorFn)
Help me - what goes wrong?

**Comment by douglasfsti** [comment]
@stogg write more details, I'm not understand your question.
I think this send the iq_node to WA server.

See the debug logging:

```
[douglas@douglastux yowsup]$ ./yowsup-cli demos -d -l 55XXXXXXXXXX:KLdDR6nt2RBF0mCsWWQHLV0Oc1w= -x 55XXXXXXXXXX /home/douglas/medo.jpg 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Groups Iq Layer - Media Layer - Privacy Layer - Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="55XXXXXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
D搎
*����|�2D
HEX:44e6908e0a0f2ad41703ab91b27c1616019a3244
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
,ſչ��;�ړ�K	b	o��~@�xZ�5=�y�6`j�����ɵe�
HEX:2cc5bfd5b981cf3ba6da93c34b0962096f958a007e1340be1b785a9c353da479e136606a9197f3b3e8c9b51865e9
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1424458055" expiration="1455994055" props="4" t="1424698734">
ʒF"gW���J��"H�x���
HEX:ca924622671f57b890e94a9ea32248bd78f8bbe7
</success>

DEBUG:yowsup.demos.mediaclient.layer:Send image in /home/douglas/medo.jpg to 55XXXXXXXXXX@s.whatsapp.net
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
<media type="image" hash="geIAKgwnTGA7MyF2CPP+/5usIscRRCH/AubCjuKjX1o=" size="42793">
</media>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1424458055" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="1">
<duplicate mimetype="image/jpeg" filehash="geIAKgwnTGA7MyF2CPP+/5usIscRRCH/AubCjuKjX1o=" url="https://mmi202.whatsapp.net/d/ArQ-oQqmnJDlw2Q3PC5SnhYcmDtFNA9q3MI2gCVT3-bK.jpg" height="552" width="736" type="image" size="42793">
</duplicate>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<message to="55XXXXXXXXXX@s.whatsapp.net" type="media" id="1424698734-2">
<media mimetype="image/jpeg" filehash="geIAKgwnTGA7MyF2CPP+/5usIscRRCH/AubCjuKjX1o=" encoding="raw" url="https://mmi202.whatsapp.net/d/ArQ-oQqmnJDlw2Q3PC5SnhYcmDtFNA9q3MI2gCVT3-bK.jpg" height="552" width="736" file="medo.jpg" type="image" size="42793">
����JFIF��      	





 $.' ",#(7),01444'9=82<.342��C			


2!!22222222222222222222222222222222222222222222222222��0@"��

���}!1AQa"q2��#B��R��$3br�	
%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz���������������������������������������������������������������������������

���w!1AQaq"2B����	#3R�br�
$4�%�&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz��������������������������������������������������������������������������
                                                                                                                               ?ㄜ��C�]&��e����@?�&y�S$���:�놉�ӕH���}}9�uM�sk�A�'�k�����Ap�&9
���O���?_Z�״�/Y�"h�!#�	�Lq�U{/0��-#b��	�A�n�1S��5���1��3ۮ�6�`<�=�;|����^i��_\�D����PV!���Ԕ�������'�c�����VŶ�څ�p����ʩа��b���f�&ѯ�gO�yq��^�6H�۹�;
           ŵ�e��x��{
                      ���"���L��u(��W�'�n���OZi�o
                                                   P�>�YO��-��=~Q���qp�2r{��j�A:[8l
���MpQ]&��X�i伺�bǔ�n���{���v��]H�V��Oc��T����%Lʎw����*M?���(��Фx^RYv�'��-^��֖�ys�*�'h�U�K�;}{R:�Q��N�弭��X�	<����Igb�p�Ѿ]��6H#�lS��
                                                                                                        H�J�����J�jS�"�7N\�9���f��[O�݀T-�s����+����U�g\xR����7�[�y��>TMٗ���N��P����O��.��O3$mA��k�Q20G��+k���	�����Z\�������+|Km)B�xQ�ǥu6�Cn#�;���[1X���2�Gb@ή�����54��+!U��;��L���gЊ��I���R�V�#�c����
HEX:ffd8ffe000104a46494600010100000100010000ffdb004300080606070605080707070909080a0c140d0c0b0b0c1912130f141d1a1f1e1d1a1c1c20242e2720222c231c1c2837292c30313434341f27393d38323c2e333432ffdb0043010909090c0b0c180d0d1832211c213232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232ffc00011080030004003012200021101031101ffc4001f0000010501010101010100000000000000000102030405060708090a0bffc400b5100002010303020403050504040000017d01020300041105122131410613516107227114328191a1082342b1c11552d1f02433627282090a161718191a25262728292a3435363738393a434445464748494a535455565758595a636465666768696a737475767778797a838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7e8e9eaf1f2f3f4f5f6f7f8f9faffc4001f0100030101010101010101010000000000000102030405060708090a0bffc400b51100020102040403040705040400010277000102031104052131061241510761711322328108144291a1b1c109233352f0156272d10a162434e125f11718191a262728292a35363738393a434445464748494a535455565758595a636465666768696a737475767778797a82838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9faffda000c03010002110311003f00e3849cf5a91643eb5d269be165beb911b4f1403fbd2679f6005324f0f4b63a9eeb8689add39511480f99d71807b67d7d39ae754db5736b9841cd27986bb5bdfb0eb9f64170161ba81b26390ae5a3c74f97a8ce3f5f5ad6d7b49d2f59d022681e18ee210023ec09c74c71d4557b2f30b9e62d2362a9dd098441cc6e11ba315383f435daff00c231a29b330fdbae16f23601a4603cb63dc63b0f7cd6f797a55e69afa45f5ccc4490968bcb5056218ca91ee31ed49401b3c11af5e2d4d6e227d863c8dcc0e0fb56c5b6bada85e470ccf185fbcaa9d0b0f5af62b8b1d266d026d1af84674f90797198d4065e803648fbdbb9af3b1f0bc5b5f865be927803068d847b0b0ed9f4ad1c22d5ccf54cded47528a0be579627dd6efbe308e3078eff00af4f5acd7f1169b76f0c50c73ee88e25594fcbc92dc1c93d7e957f51f0aea37170f232727b86ae6afb413a5b1f386c0cd9c8e79ac6536a2d23a2924e4ae6c6aba8d8e96d06a51a4ee2e5bcadbbc158c91d093c9a86e7c5496762be709dd1be5d90c803364823b76c53b4cf0dddf88ec7cb4dad0870d97f515d2689a358f869e4bcba8e29ae62c794c46ed9feee7bfbd4c2768de45d48de5681cd4f6301b59754bcd0ee9d25064cca8e7713e991d7d31d2a4d3fc5c8f628d1c0d0a4781b5e525976f6278af42d1b5ebabad696ee7973b5182a962768e955fc4be13b7d7b523a8451c50b48804a15000ec3f8beb8a74ab46a53e78ed722a5374e5cb239bf08f88df566bfbb5b4f96dd80542dbb7313d7078181ce2bbeb7b88b558448c8893a315f971fbc40787c0f5ebf8d70b068bff08d4ae5a2334126371418643d88aec7c33e4cf1f9a321dba92b826b5a734f4329ad0d592cd64e0d675c7852d2f5c3ca3711eb5ba179ab11ad3e544dd9970e8c96964e90a85014e315cccde14fb6c22edeea4f33246d419fa66bd15132304706aa9d2b6b9685dd09fee9fe95955a5ce6f4aaf21c1da784b52b7c4b6d2942e3077819519ec7a5753616b2436e239b3bfb83eb5b315890c1a532ca4762401fceaee19bf802fbf53534a8a82b2155acea3bb318e9104c9fbd8867d08a96df4982dffd5205fa56a88e9e2302ba631b1ced9fffd9
</media>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1424698734" from="55XXXXXXXXXX@s.whatsapp.net" id="1424698734-2" class="message">
</ack>

INFO:yowsup.demos.mediaclient.layer:Message sent
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Requested
```

**Comment by stogg** [comment]
Sorry, im newbie in python...
Cant get debug log, but do some modification in def main
    def main(self):
        for target in self.getProp(self.__class__.PROP_MESSAGES, []):
            jid, path = target
            jid = '%s@s.whatsapp.net' % jid
            self.MEDIA_TYPE = "image"
            print(jid,self.MEDIA_TYPE)
        logger.debug("Send %s in %s to %s" % (self.MEDIA_TYPE, path, jid))
        entity = None
        entity = RequestUploadIqProtocolEntity(RequestUploadIqProtocolEntity.MEDIA_TYPE_IMAGE, filePath=path)
        print(entity)
        successFn = lambda successEntity, originalEntity: self.onRequestUploadResult(jid, path,successEntity, originalEntity)
        print(successFn)
        errorFn = lambda errorEntity, originalEntity: self.onRequestUploadError(jid, path,errorEntity, originalEntity)
        print(errorFn)
        self._sendIq(entity, successFn, errorFn) 

Output is:
Iq:
ID: 1
Type: set
xmlns: w:m
to: s.whatsapp.net
Media Type: image
B64Hash: 3yHs3jkmTF0E+E/ZlZ7B1I3taKEpqsF8o1FksLNBUAc=
Size: 134772

<function <lambda> at 0x01911230>
<function <lambda> at 0x01911270>

and nothing more... no errors, no continue...

**Comment by vijayrajput** [comment]
I am also facing same issue as stogg commented. Kindly help 
sending stuck at last point there:
self._sendIq(entity, successFn, errorFn)

Here my trace log.
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
INFO:run:[(u'919560646797', u'66846322')]
testing loop
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="918375896729" mechanism="WAUTH-2">
▒l▒Qǲ6▒W▒D▒nFhj▒▒9▒]▒O▒▒ ׸▒▒׸{▒▒▒V[▒▒
HEX:916cf0959e51c7b2369b57d044c56e1646686ab6e28739c65dff4fa58720d7b81ae17fa8d7b87bb0aee7565b80a0
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒ጔ▒S▒U2A#o{▒▒▒
HEX:f61bf5e18c94fa5388553241236f7b04baaccc12
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒vOy▒▒▒▒A▒LKO▒▒z
▒a> ▒▒E^)▒+Pf2Ϊ▒▒\
HEX:07d1764f79b198a0bf0141ad4c4b4fa21bd5f47a0af024600808613e200fb7d7455e29842b506632ceaaedfc195c
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1427707666" expiration="1459243666" props="4" t="1429011677">
▒▒[▒16▒▒▒i▒▒▒O▒a
HEX:e6b0f17f5b941c3114369ab0cb69f49ce54fa161
</success>

INFO:layer:onSuccess
919560646797 and 66846322
INFO:layer:target:91956064679766846322
/cygdrive/c/Python27/WhatsAppProject/123.jpg
('919560646797@s.whatsapp.net', 'image')
Iq:
ID: 1
Type: set
xmlns: w:m
to: s.whatsapp.net
Media Type: image
B64Hash: FYHZkqr/v9qrgC3tGrk1XuZWbRsc85YZhxops49CnmI=
Size: 6090

after sendIQ
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1427707666" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>

**Comment by Narendra-Kumar** [comment]
updated latest yowsup.....

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 232, in process
    self.startMediaClient()
  File "yowsup-cli", line 294, in startMediaClient
    stack.start()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\stack.py", line 36, in start
    self.stack.loop()
  File "C:\Python27\yowsup-master\yowsup\stacks\yowstack.py", line 173, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 48, in handle_read
    self.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 55, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 161, in receive
    s.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 102, in receive
    recv(node)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_authentication.py", line 55, in handleSuccess
    self.toUpper(nodeEntity)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\interface\interface.py", line 71, in receive
    self.callbacks[entityType](entity)
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 30, in onSuccess
    self.main()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 98, in main
    self.MEDIA_TYPE = MediaDiscover.getMediaType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 190, in getMediaType
    mediaType = MediaDiscover.fromMimeType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 162, in fromMimeType
    mimeType = magic.from_file(path, mime=True)
  File "build\bdist.win32\egg\magic.py", line 135, in from_file
  File "build\bdist.win32\egg\magic.py", line 123, in _get_magic_type
  File "build\bdist.win32\egg\magic.py", line 59, in __init__
WindowsError: exception: access violation writing 0x00000002
Exception AttributeError: "Magic instance has no attribute 'cookie'" in <bound method Magic.__del__ of <magic.Magic instance at 0x02E51C38>> ignored


getting above error

**Comment by Narendra-Kumar** [comment]
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 232, in process
    self.startMediaClient()
  File "yowsup-cli", line 294, in startMediaClient
    stack.start()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\stack.py", line 36, in start
    self.stack.loop()
  File "C:\Python27\yowsup-master\yowsup\stacks\yowstack.py", line 173, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 48, in handle_read
    self.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 55, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 161, in receive
    s.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 102, in receive
    recv(node)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_authentication.py", line 55, in handleSuccess
    self.toUpper(nodeEntity)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\interface\interface.py", line 71, in receive
    self.callbacks[entityType](entity)
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 30, in onSuccess
    self.main()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 98, in main
    self.MEDIA_TYPE = MediaDiscover.getMediaType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 190, in getMediaType
    mediaType = MediaDiscover.fromMimeType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 162, in fromMimeType
    mimeType = magic.from_file(path, mime=True)
  File "build\bdist.win32\egg\magic.py", line 135, in from_file
  File "build\bdist.win32\egg\magic.py", line 123, in _get_magic_type
  File "build\bdist.win32\egg\magic.py", line 59, in __init__
WindowsError: exception: access violation writing 0x00000002
Exception AttributeError: "Magic instance has no attribute 'cookie'" in <bound method Magic.__del__ of <magic.Magic instance at 0x02E51C38>> ignored

getting above error

**Comment by joyarzun** [comment]
FYI
I merged this PR into my fork with some conflict. Then, I exec the command

```
yowsup-cli demos -c config -x "5695945XXXX" ./picam/i20160110_062244PM.jpg
```
I get a warning

```
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
```

Please merge this PR into tgalal/yowsup

**Comment by kitsontam** [comment]
hi all,

i follow the file changes, but not work for me. would anyone can help on this? anything i miss to modify?

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "/home/pi/tgalal/yowsup/yowsup-cli", line 387, in <module>
    if not parser.process():
  File "/home/pi/tgalal/yowsup/yowsup-cli", line 278, in process
    self.startMediaClient()
  File "/home/pi/tgalal/yowsup/yowsup-cli", line 342, in startMediaClient
    stack = mediaclient.SendMediaStack(credentials, [(self.args["media"][0], self.args["media"][1])])
  File "/home/pi/tgalal/yowsup/yowsup/demos/mediaclient/stack.py", line 31, in __init__
    self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
AttributeError: 'module' object has no attribute 'CURRENT_ENV'

**Comment by anhvu-sg** [comment]
hi @tgalal , _yowsup_ is amazing. I just have a question when will this PR is merged :)

**Comment by Exosylver** [comment]
@douglasfsti Does this also work for videos, or only pictures currently?

**Pull request closed without merging**
