### PR TITLE
Add yowsup-utils for getting new apk, get version and md5 dex classes

### PR DESCRIPTION
**Pull request by masbog**
hi, i was added some utilities for improve this yowsup 😉

output will be like this : 

$ python yowsup-utils.py
URL download for APK : https://download.apkpure.com/b/apk/Y29tLndoYXRzYXBwXzQ1MTk1MV9kNmI4NjE3OA?_fn=V2hhdHNBcHAgTWVzc2VuZ2VyX3YyLjE3LjI5Nl9hcGtwdXJlLmNvbS5hcGs%3D&k=52cdfa1d5a064cc6980afcd9025399f859a4056a&as=e6da2a0ca32bea713a4d46eca75b4cf059a162e2&_p=Y29tLndoYXRzYXBw&c=1%7CCOMMUNICATION

=== Processing APK ===
Version: 2.17.296
ClassesDex: YrJNPljM3TuNFPIOZ+jziw==

### CODE REVIEW

**Comment by mgp25** [comment]
You are infringing the copyright and you have not even put a link to the original code.

Original code can be found here: [dexMD5.py](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py)

Repository: https://github.com/mgp25/classesMD5-64

Also it is very risky to download WhatsApp apk from non trusted sites. WhatsApp apk **MUST** be downloaded from Play Store or WhatsApp Official website. Never from non trusted websites where any user can upload any modified apk.

Regards

**Comment by masbog** [comment]
any idea for downloading the apk from play via terminal? 😢
sorry about the copyright, i will add it soon...

**Comment by drbeat** [comment]
just do wget LOL
wget https://www.cdn.whatsapp.net/android/2.17.314/WhatsApp.apk

**Comment by masbog** [comment]
@drbeat nice LOL :)) preparing for getting latest version 👍

**Pull request closed without merging**
