### PR TITLE
Set  _VERSION = "2.17.221" in env_android.py

### PR DESCRIPTION
**Pull request by gauravssnl**

### CODE REVIEW

**Comment by naupa** [comment]
I tested it by calling yowsup-cli registration --requestcode sms --phone 49... --cc 49 --mcc 262 --mnc 23 --env android

IT WORKED FINE.

**Comment by gauravssnl** [comment]
for sending message,android env will not work.just try that. I had to use s40 env for that @naupa

**Comment by Bluscream** [comment]
already outdated, gives me a
```
blu@homeserver:/usr/local/lib/python3.5/dist-packages/yowsup/env$ yowsup-cli registration -C 49 -r sms -p XXXXX
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:b'{"login":"XXXXX","status":"fail","reason":"old_version"}\n'
login: b'XXXXX'
reason: b'old_version'
status: b'fail'
```

**Comment by gauravssnl** [comment]
That's what I told you.you need to use s40 env for yowsup-cli .you can do that by using  yowsup-cli -E s40 command.just add that option ,it will work then.Try it @naupa

**Comment by Bluscream** [comment]
@gauravssnl yeah thank you i already got it fixed by also applying #2118

**Comment by Saleh7** [comment]
```shell
root@x7:~/yowsup# ./yowsup-cli registration -C 1 -r sms -p 1480xx9xxx2 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"1480xx9xxx2","status":"fail","reason":"too_recent","retry_after":947,"sms_wait":947,"voice_wait":0}

status: fail
retry_after: 947
reason: too_recent
```

**Comment by gauravssnl** [comment]
@Saleh7  I think you need to wait for some time and retry again later

**Comment by guilhermeluisdomingues** [comment]
https://github.com/tgalal/yowsup/pull/2119/commits/ae440780894f97a0486da9d3c52e0d6a0a8bdb81 worked for me! 
My Whatsapp version is 2.17.395 but worked fine :)

Thanks!

**Pull request merged**
