### PR TITLE
Push participant when sending read receipt

### LINKED ISSUE #524: Sending read receipts in groups
As given in the [sample app](https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app#layerpy-iv) on the wiki, I [send receipts](https://github.com/tcoenraad/inter-actief-botje/blob/master/layer.py#L26) after receiving any message. This works as expected in private conversations, in which I get blue checks and I can see a seen and delivered time in the message info dialog.

However, this does not work in groups, and the delivery and read check remains grey. In the message info dialog, the message does not seem to be delivered to the Yowsup client, although the message is in fact passed through Yowsup. Can you please help? A similar issue is described in the WhatsAPI issue tracker: https://github.com/mgp25/WhatsAPI-Official/issues/153

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7576203-sending-read-receipts-in-groups?utm_campaign=plugin&utm_content=tracker%2F298781&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F298781&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tcoenraad**
Fixes #524.

### CODE REVIEW

**Comment by tgalal** [comment]
Thanks a lot!

**Comment by msshapira** [comment]
@tgalal I'm not sure this feature actualy works. I hoped that once sending a "read" reciept together with the "participant" attribute - the group message sender from an android device would see the yowsup user under the "read" list. However, this is not the case....
My code (based on the echo client):
```
def onTextMessage(self,messageProtocolEntity):
receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(),messageProtocolEntity.getFrom(), read=True, participant=self.getOwnJid())
```

**Comment by tcoenraad** [comment]
It works in this way: 

```
receipt = OutgoingReceiptProtocolEntity(message_protocol_entity.getId(), message_protocol_entity.getFrom(), 'read', message_protocol_entity.getParticipant())
```

See also this commit in my project:
https://github.com/tcoenraad/inter-actief-botje/commit/f00814a1ac84f4a2a15d179d952e3f87c382a213

**Comment by msshapira** [comment]
Thanks

**Pull request merged**
