### PR TITLE
remove tests that test nothing

### PR DESCRIPTION
**Pull request by magicgoose**
`class KeyStreamTest`
the last 2 tests do not check anything, they just run the code and the results are not used at all
this is misleading and doesn't do any good

### CODE REVIEW

**Comment by magicgoose** [comment]
3 days…

**Comment by mgp25** [comment]
@magicgoose what happens? People have lifes too, we arent always in from of a computer, be patient!

When @tgalal is free, he will check it and if everything is finehe will merge this pull request.

Conclusion: Be patient

**Comment by magicgoose** [comment]
@mgp25 That's true, and I really do not like to be _that guy._
…But previously there was a paragraph in the wiki saying something about 48 hours period. I checked it now, and it was [deleted](https://github.com/tgalal/yowsup/wiki/Yowsup-development,-debugging,-maintainance-and-sanity/_compare/9d11a841c2dac355408c87eb3c225549f9c49e6b...92e6a72a69291bff40d8cb76d452edfc34c2a3cb). I should have checked it before posting (and not post it), that's my fault. I'm sorry.

**Comment by tgalal** [comment]
If encoding/decoding fails, an exception will be raised causing the test to fail. Ideally the exception should be caught and fail the test more gracefully.

**Pull request closed without merging**
