### PR TITLE
demo for checking valid whatsapp contact added

### PR DESCRIPTION
**Pull request by girish946**
I was also facing the same issue as https://github.com/tgalal/yowsup/issues/609.
so I've just added a demo to check if the given contact number is a valid whatsapp contact.
the command line for the same goes like 
yowsup-cli demos -d -l username:password -S contact

### CODE REVIEW

**Comment by tgalal** [comment]
Thanks!

**Comment by ernany** [comment]
Excuse the question, I am not managing to identify when more is valid or not valid running this command.
can you help me?

**Comment by girish946** [comment]
@ernany  please post more details... exactly what issue you are facing....

**Comment by ernany** [comment]
the return of the command and always the same even with valid and invalid number
I am using:

demos -d --login 5511998453679:CktJkpX2miHevQ12QQX6IYHAIg= -S 55119702...

**Pull request merged**
