### PR TITLE
Update md5 class and version to 2.18.133

### PR DESCRIPTION
**Pull request by 0rC0**
see #2518 and #2546

### CODE REVIEW

**Comment by d4nd** [comment]
What is going on with this repository?
It's a great project indeed, but it looks dead

**Comment by IsaacG** [comment]
Sadly, even with the MD5_CLASSES and VERSION updated, I'm still getting the old_version error message.

**Comment by Hattshire** [comment]
https://coderus.openrepos.net/whitesoft/whatsapp_scratch
You can use **a** and **d**

**Comment by marcosmarchiore** [comment]
@Hattshire  you work yowsup-cli and not problem?

**Pull request closed without merging**
