### PR TITLE
upload image: MediaIqProtocolEntity

### PR DESCRIPTION
**Pull request by debianitram**

### CODE REVIEW

**Comment by aesedepece** [comment]
You shouldn't commit backup files (the ones ending with "~" automatically generated by gedit and other editors).

**Comment by debianitram** [comment]
Forgiveness. I didn't realize!

**Comment by oxan** [comment]
There are quite a few debug messages to stdout that should be using the logger. 

I'm also wondering, wouldn't it be better to use a built-in HTTP/MIME implementation instead of spelling out our own HTTP and MIME?

**Comment by tgalal** [comment]
@debianitram are you going to remove the backup files?

**Comment by debianitram** [comment]
Yes of course. I do it. Tomorrow I'll upload all with an example in demo cli.

**Comment by viksit** [comment]
@debianitram great work - any updates on your commit?

**Pull request closed without merging**
