### PR TITLE
V2Padding fixed

### PR DESCRIPTION
**Pull request by jlguardi**
Fixed v2 padding

### CODE REVIEW

**Comment by fsmit3** [comment]
@jlguardi I tried your version in this pull request and when receiving an encrypted image from an Android device I get this:

  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
    def onMessage(self, messageProtocolEntity):
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
    import hashlib
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 117, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    ID = hashlib.sha224(senderJId + "_" + receiverJId + "_" + messageId).hexdigest(),
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 281, in handleWhisperMessage

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_media/layer.py", line 40, in recvMessageStanza
    self.onTextMessage(messageProtocolEntity, environmentname)
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'

Am I doing something wrong here?

**Comment by jlguardi** [comment]
@fsmit3 Encrypted images are not supported. Use s40 env instead.

**Comment by jodersus** [comment]
Hi

I have made all the changes from last night, I am using the new s40 env and the updated V2 padding fix, I delete axolotl db and restarted the yowsup-cli but still getting the same error as @fsmit3 

```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 255, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 281, in handleWhisperMessage
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'
```

Please help
A

**Comment by yniv** [comment]
same here... this is a serious issue...!

**Comment by moyamo** [comment]
tgalal has been inactive for a while. Could someone with more time on their hands create a temporary repo with all the fixes (pull requests) in it? I think we should get a temporary maintainer until tgalal comes back.

After applying this fix. I'm unable send messages: I get a ping timeout after sending a message.

**Comment by fsmit3** [comment]
@jlguardi switching to s40 does solve the issue

**Comment by yniv** [comment]
@fsmit3 no it doesn't fix this. i'm using the new s40 env and having this issue...

**Comment by fsmit3** [comment]
@yniv Sorry typo I meant doesn't

**Comment by thundergreen** [comment]
I totally agree with @moyamo . The messup here is more confusing than fixing! Can somone please add a repo with all fixes and commits.

**Comment by schoerg** [comment]
@moyamo last commit from him was in February.

**Comment by ronromer** [comment]
nice.. work here.. (y)

**Comment by sphaero** [comment]
This PR fixed sending random padded messages with the echo client for me as well.

However where are the padded bytes coming from.... encryption?

**Pull request closed without merging**
