### PR TITLE
close socket before create

### PR DESCRIPTION
**Pull request by msshapira**
under windows broadcasting EVENT_STATE_CONNECT after socket stops working doesn't reconnect.
Added a close() before attemting to connect

### CODE REVIEW

**Comment by msshapira** [comment]
so my code looks something like this:
```
 while True:
            try:
                self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
                self.stack.loop(timeout = 0.5, discrete = 0.5)
                
            except AuthError as e:
                logger.exception("AuthError")
                break
            except Exception as e:
                logger.exception("Other Error")
                time.sleep(20)
```

**Comment by tgalal** [comment]
This change causes error with at least python2.7  though..

**Comment by msshapira** [comment]
@tgalal can you please merge this. I can't find a way to recover in windows without this

**Comment by msshapira** [comment]
(oh, It doesn't break 2.7 anymore...)

**Comment by msshapira** [comment]
(oh, It doesn't break 2.7 anymore...)

**Comment by msshapira** [comment]
@tgalal bump

**Pull request closed without merging**
