### PR TITLE
updated to android and whatsapp 2.12.440

### LINKED ISSUE #1335: Unable to do registration
My yowsup version:

yowsup-cli v2.0.13
Using yowsup v2.4.48

While trying registration, gives status: fail & reason: old_version

Here, is my command and stack trace (while doing --debug):

**python yowsup-cli registration --config mydetails --requestcode sms --debug**
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=91&in=XXXXXXXXXX&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=a93834b0cf1b70077b89118833dc6e0a&id=%0C%3A%14%D3%DB%B4v%18r%E9%FEaW%5Bb%0D%C7%2B%AD%2F
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=XXXXXXXXXX&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=a93834b0cf1b70077b89118833dc6e0a&id=%0C%3A%14%D3%DB%B4v%18r%E9%FEaW%5Bb%0D%C7%2B%AD%2F
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

I have read older post, but they somehow didn't solved my problem, as I'm already using latest code.

PS: WhatsApp has released a newer version, few days back, is it because of that registration is not working?

### PR DESCRIPTION
**Pull request by jlguardi**
Fix #1335 
Replaced Android env_file with 2.12.440 information.
Included some params during code request.
Forced android env in http/registration protocols

### CODE REVIEW

**Comment by abigoroth** [comment]
I just cloned this repo and replace all three files which @jlguardi did. But still get the same error :

Yakobs-MacBook-Pro:yowsup akob$ yowsup-cli registration --requestcode sms --phone 60XXXXXXXXXX --cc 60 --mcc 502 --mnc 16
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
@abigoroth really?? I've registered a line 2 hours ago and worked.

Add -d flag and post logs.

**Comment by abigoroth** [comment]
Yakobs-MacBook-Pro:yowsup akob$ yowsup-cli registration --requestcode sms --phone 60172931521 --cc 601 --mcc 502 --mnc 16
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
Yakobs-MacBook-Pro:yowsup akob$ yowsup-cli registration --requestcode sms --phone 60172931521 --cc 601 --mcc 502 --mnc 16 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=601&in=72931521&lc=GB&lg=en&sim_mcc=502&sim_mnc=016&method=sms&token=fc5cf16b1e498d49869aa1cb93ae7ecd&id=%B0I%989%5E%ED%F8%9CF7%EAc%B1%DD%F6K%8C%B3%8B%CB
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=601&in=72931521&lc=GB&lg=en&sim_mcc=502&sim_mnc=016&method=sms&token=fc5cf16b1e498d49869aa1cb93ae7ecd&id=%B0I%989%5E%ED%F8%9CF7%EAc%B1%DD%F6K%8C%B3%8B%CB
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

**Comment by jlguardi** [comment]
@abigoroth You aren't using #1336 due to some parameters are missing in the http GET. Try to download my branch or apply again the patch.

**Comment by abigoroth** [comment]
sorry noob here. How can I download #1336 ? I cannot find any download link or .git to clone.

**Comment by jlguardi** [comment]
@abigoroth go to https://github.com/jlguardi/yowsup/tree/Android_2.12.440

**Comment by abigoroth** [comment]
still having the same problem, on MAC OS El Capitan, 

Yakobs-MacBook-Pro:yowsup akob$ yowsup-cli registration --requestcode sms --phone 60XXXXXXXXX --cc 60 --mcc 502 --mnc 16 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=60&in=XXXXXXXXX&lc=GB&lg=en&sim_mcc=502&sim_mnc=016&method=sms&token=d55c8a2c16b9727644a184a196cccd7f&id=z%A7%F2vv%D1%88%40%D4%D0%0D%0A%87%E1%DE%81%90%B3G%B6
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=60&in=XXXXXXXXX&lc=GB&lg=en&sim_mcc=502&sim_mnc=016&method=sms&token=d55c8a2c16b9727644a184a196cccd7f&id=z%A7%F2vv%D1%88%40%D4%D0%0D%0A%87%E1%DE%81%90%B3G%B6
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
@abigoroth y y still using master code. Probably you've installed yowsup and your PYTHONPATH is undefined.
Download my branch and unzip it. Go in. Export PYTHONPATH=$PWD and run ./yowsup-cli...

**Comment by abigoroth** [comment]
thanks @jlquardi , it worked. I need to rember to export PYTHONPATH=$PWD to
each another python projects that I cloned/download right?

**Comment by abigoroth** [comment]
now having trouble with this :

Error: You must specify a configuration method .

Another thing, where should I get the password?  :
--login phone:b64password

**Comment by jlguardi** [comment]
./yowsup-cli registration -C cc -p ccphone -r sms -d
You get sms code
./yowsup-cli registration -C cc -p ccphone -R code -d
Now you get password
./yowsup-cli registration -l ccphone:password -y -d

**Comment by abigoroth** [comment]
thanks @jlguardi ! It worked!

Now I need this to interfaced with my Ruby on Rails application.

Any idea ?

**Comment by Mirdrack** [comment]
This totally works for me i update the files, reinstall and register my number 
@abigoroth did you try to reinstall?

**Comment by Shakthi88** [comment]
@jlguardi 
i'm getting "registration: error: unrecognized arguments: -l XXXX:pwddd -y"   while trying the 3rd step in registration  ./yowsup-cli registration -l ccphone:password -y -d
any suggestion appreciated, Thanks

**Comment by jlguardi** [comment]
@Shakthi88 so sorry, I've a mistake in my comment (fixed now). When I said "./yowsup-cli registration -l ccphone:password -y -d" I meant "./yowsup-cli demos -l ccphone:password -y -d".

**Comment by Shakthi88** [comment]
@jlguardi , great  thanks a lot .... i'm able to login now

**Comment by abigoroth** [comment]
I don't understand why I get this error below. I cannot send message :

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by acondoriml** [comment]
@jlguardi

Hi, 

I cloned this repo and  Install yowsup again and It's working, I haven't the problem the "old_version"
So, I send a new registration and all was fine:

> INFO:yowsup.common.http.warequest:{"status":"ok","login":"5XXXXXXX0","type":"existing","pw":"XXXXXXXXXXXXX","expiration":4444444444.0,"kind":"free","price":"US$0.99","cost":"0.99","currency":"USD","price_expiration":1461802275}
> 
> status: ok
> kind: free
> ..........
> ........

I changed all conf files with the new password and re-start my app but I'm getting a new error:

> WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
> 2016-03-25 14:29:55,944  WARNING      Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
> Traceback (most recent call last):
>   File "./run.py", line 50, in <module>
>     stack.loop() #this is the program main loop`
>   File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
>   File "/usr/lib/python2.7/asyncore.py", line 216, in loop
>     poll_fun(timeout, map)
>   File "/usr/lib/python2.7/asyncore.py", line 156, in poll
>     read(obj)
>   File "/usr/lib/python2.7/asyncore.py", line 87, in read
>     obj.handle_error()
>   File "/usr/lib/python2.7/asyncore.py", line 83, in read
>     obj.handle_read_event()
>   File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
>     self.handle_read()
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
>     try:
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
>     dataClima.append(diccionario["main"])
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
>     logger.setLevel(logging.INFO)  # Setea el level de logueo
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
>     #allowedPersons=['5491133586472','5491137811514','NUMBER_ALLOWED3','NUMBER_ALLOWED4']
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
>     handler.setFormatter(formatter)  # setea el formatter al handler
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
>     from yowsup.layers.protocol_messages.protocolentities  import TextMessageProtocolEntity
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 126, in receive
> 
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 77, in handleFailure
> yowsup.layers.auth.autherror.AuthError: not-authorized
> 

Any solution or suggestion?

Ty a lot!

**Comment by jlguardi** [comment]
@acondromi clone my master branch instead of this.

**Comment by abigoroth** [comment]
I have the same issue like @acondromi :

Auth Error, reason not-authorized

**Comment by Mirdrack** [comment]
I apply the changes of this pull to my project and that works to register 
It works a few days but now I'm getting the **Auth Error, reason not-authorized** but I don't know if I should talking about this on this report or open a new Issue
But if somebody know what is happening it will be good to know

Thanks

**Comment by AshutoshKumarAnand** [comment]
I am using the latest version but still i am getting error reason as old_version

**Pull request merged**
