### PR TITLE
#1181: Event callback feature implementation. YowInterfaceLayer

### PR DESCRIPTION
**Pull request by jlmadurga**
As described in #1181 decorator for event callbacks is implemented. Nothing reinvented just following the ProtocolEntity callback scheme for this implementation.
Event callback added to yowsup-cli.

Moreover, I found `YowLayerTest` not enough for testing events. I have added some functionality for `emitEvent` and `broadcastEvent` testing.

### CODE REVIEW

**Comment by tgalal** [comment]
While I like that improvement as it would make code much readable, I think it makes sense to have decoration available on the YowLayer level, and not just on YowInterfaceLayer right ?  Because all layers are handling events, while in case of ProtocolEntityCallback it's YowInterfaceLayer specific

**Comment by jlmadurga** [comment]
You are right @tgalal. I will move it to YowLayer.

**Comment by jlmadurga** [comment]
While testing I think have found a bug in `YowStanzaRegulator ` constructor:
```
    def __init__(self):
        super(YowLayer, self).__init__()
        self.buf = bytearray()
        self.enabled = False
```
Corrected with correct class to call `super.__init__()`
```
    def __init__(self):
        super(YowStanzaRegulator, self).__init__()
        self.buf = bytearray()
        self.enabled = False
```

**Comment by jlmadurga** [comment]
I have just fixed an issue making some more tests with CLI and python3. For `YowNetworkLayer` is necessary to have `asyncore` initialized before `inspect.getmembers` get its method to apply `EventCallback` in `YowLayer.__init__(self)`. It was only experienced in python3.
```
class YowNetworkLayer(YowLayer, asyncore.dispatcher_with_send):
    def __init__(self):
        asyncore.dispatcher.__init__(self)
        YowLayer.__init__(self)
        self.interface = YowNetworkLayerInterface(self)
        httpProxy = HttpProxy.getFromEnviron()
        proxyHandler = None
```

**Pull request merged**
