### PR TITLE
[WIP] A easier interface to using yowsup (YowsupApp)

### PR DESCRIPTION
**Pull request by moyamo**
**DO NOT MERGE YET. WORK IN PROGRESS**
# Problem

Most of the issues that plague the yowsup issue tracker are I-can't-get-it-to-work issues. This is due to
- The unorthodox Yowsup API
- Whatsapp will disconnect you if you violate their protocol
- It is easy to make yowsup violate whatsapp's protocol
- Lack of clear documentation
### Stack and Layer

To use yowsup the user must create two classes. One for the stack and one for the layer. It would be easier if the user just needed to create one class.
### ProtocolEntities

To send a message in Yowsup you would do this

``` python
messageEntity = TextMessageProtocolEntity(message, to = to)
self.sendEntity(messageEntity)
```

It would be much easier if you could just do this

``` python
self.sendTextMessage(to, message)
```

To receive a message is something like this:

``` python
@ProtocolEntityCallback('message')
def onMessage(entity):
    _from = entity._from
   message = entity.message
```

This would be easier

``` python
def onMessage(_from, message):
    pass
```
### JIDs

Yowsup should not make the developer deal with JIDs. These should be handled transparently as they are redundant.
### Acks

The developer is required to send Acks. While this offers a lot of control to the developers it also adds a lot of boilerplate. Whatsapp will disconnect you if you do not ack every stanza. Lots of devs don't know this and end up getting frequently disconnected.
### Imports (entities)

Generally the MyAppLayer has dozens of imports. This is because entities that need to be sent and received are spread across multiple files. If instead of sending entities we use methods we can get rid of almost all imports.
# Solution

What I propose is a well-documented API similar to [Chat-API](https://github.com/WHAnonymous/Chat-API) to combat these problems

I've come up with an initial implementation but it is still incomplete.

The user will access this API by extending the YowsupApp class. This is the only yowsup class the user needs to interact with. There will be three types of functions in this API: requests, events, and once-offs.

A request function starts with `request`. It usually sends an Iq. The last two arguments will be onSuccess and onFailure, which are callbacks to the Iqs response

Event functions start with `on` these should be overridden by the user. These are called when messages, notifications or presence is received.

Once-off functions usually start with `send`. These act like ordinary methods and are used to send messages, presence etc.

The API should automatically send acks (and maybe receipts) as I think this is one of the most common violations that causes whatsapp to disconnect users.

All contacts should be represented by contact numbers (e.g. `21902192121`) and not JIDs (e.g. `21902192121@s.whatsapp.net`). Groups should look like this `21902192121-149830293`. The YowsupApp class will do all the translation between contact numbers and JIDs transparently.

A typical echo client should look something like this. (Note that the current implementation doesn't work like this)

``` python
import yowsup.YowsupApp

class Echo(YowsupApp):
    def __init__(self, username, password):
        self.login(username, password)
    def onTextMessage(self, from, message, *args):
        self.sendMessage(from, message)
```

As I've said before this is still incomplete. I would really appreciate help from anyone who can complete this.

### CODE REVIEW

**Comment by jlmadurga** [comment]
Great job! I think it is a good idea to simplify with something kind of  `YowsupApp`. I think it will be easier not to have to deal with stacks and layers at first. This is my quick review/feedback:

* **Layers:** layers are great so must be something in constructor to include more layers between the top app layer and the core layers. Just to have some intermediate layers as `yowlayer-storage`
* **Stack.Loop:**where are you including this? I will include it in a `listen` independent method just to call it easy from other thread or tasks
* **Auto Acks**:  Agree. Maybe just add some configuration parameter not to do it for some especial cases
* **Entity decapsulation**: Great idea! I think it is more clear to work with function parameters than entities. Anyway it will be harder to maintain if entities changes

**Comment by moyamo** [comment]
Entity decapsulation: I was thinking that we could extract the most important parameters that are the least likely to change and then pass in the entity as the final argument. This allows entities to be a bit more flexible.

**Comment by Saadkhalid-mm** [comment]
Great initiative!
Another advanced thing we can do in the future, to make it more easily usable, is that we study WhatApp's blocking patterns and then create checks to avoid doing that. Since WhatApp has started blocking IPs as well now. Even basic registration requests can cause blocking if not done carefully.

**Comment by jodersus** [comment]
I understand why you want to do this, but please do not take away the flexibility and control Yowsup allows currently. I guess there could be a 'nice and easy' YowsupApp with a lot of predetermined standards, but that you can override for fine-tuning.
I think the biggest win would be a deep, thorough documentation.

**Comment by dieterhatnkleinen** [comment]
Any news on this? I'd like to use this for a simple event based app im developing

**Pull request closed without merging**
