### PR TITLE
Twisted based client, initial import.

### PR DESCRIPTION
**Pull request by a-d-j-i**

### CODE REVIEW

**Comment by tgalal** [comment]
Can you please at least explain what it exactly does ?

**Comment by a-d-j-i** [comment]
A network layer based on twisted reactor instead of asyncore.
Twisted has a lot of other protocols implemented, so if you want to do a mail <-> yowsup bridge it is easyer to do with twisted.

**Comment by wladston** [comment]
Twisted isn't Python-3 ready: https://twistedmatrix.com/trac/milestone/Python-3.x  Asyncore is!

**Comment by a-d-j-i** [comment]
The problem I faced is that the imap, pop and sendmail implementations of the python lib seem to use blocking sockets and are not compatible with asyncore. This force me to use threads and queues to integrate everything. I thing a that twisted reactor is a cleaner alternative and also twisted has a scheduler to run tasks every some seconds.

**Pull request closed without merging**
