### PR TITLE
Add receive client

### PR DESCRIPTION
**Pull request by cutec-chris**
Thia adds a simple message receive client (like the send client) based on echo client

### CODE REVIEW

**Comment by tgalal** [comment]
Thanks! Only thing is that we must send message receipts otherwise after a while we stop receiving new messages, and we'll keep receiving same messages on each connection.

**Comment by CODeRUS** [comment]
In addition you will be kicked after timeout if not sending receipt

**Comment by cutec-chris** [comment]
good to know, i will try to add this

**Comment by cutec-chris** [comment]
added sending receipt

**Comment by tgalal** [comment]
Can you change variables and class names to match what it does ?

**Pull request closed without merging**
