### PR TITLE
forward method: remove notify token

### PR DESCRIPTION
**Pull request by jlguardi**
If not, original message notify is reused.

### CODE REVIEW

**Comment by tgalal** [comment]
I think it should be totally removed, outgoing messages never have "notify" explicitly set by sender, same thing for "t", "retry" and "offline" attributes that are present in incoming, but should not be in outgoing messages. But I think this all should be enforced in MessageProtocolEntity.toProtocolTreeNode instead

**Comment by jlguardi** [comment]
Ok. I didn't known. I'll remove all this attributes here and in toProtocolTreeNode and I'll propose again the pull.

**Comment by jlguardi** [comment]
@tgalal You were right, it is clear in toProtocolTreeNode. Ready to merge if you agree.

**Comment by jlguardi** [comment]
@tgalal the pull request is ready for some time. Do you agree this pull?

**Comment by tgalal** [comment]
sorry for delaying that. I'll review it asap

**Comment by tgalal** [comment]
merged into develop. Sorry again that it took that long

**Pull request merged**
