### PR TITLE
Update env_android.py

### PR DESCRIPTION
**Pull request by dedmen**
update to 2.12.94

### CODE REVIEW

**Comment by mgp25** [comment]
@dedmen actually you should use this `7Ai8bMBxBeO5SFSLutDs8A==` with `2.12.96`

Regards

**Comment by dedmen** [comment]
I Only had 2.12.94 on my phone... I updated my patch

**Comment by mgp25** [comment]
@dedmen we have done a script to check latest version, pretty easy to manage if you use json: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Regards

**Comment by krmboya** [comment]
I started getting the error `Auth Error, reason not-authorized` yesterday, I've tried this patch but I'm still getting the same error.

**Comment by krmboya** [comment]
@mgp25 I'm trying to understand the JSON response returned by https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Would you mind explaining what the keys 'a' to 'h' stand for?

**Comment by mgp25** [comment]
e: s40 ver
h: releasetime s40

d: android ver
a: classes dex md5 base64

**Comment by krmboya** [comment]
Okay, thanks!!

**Pull request merged**
