### PR TITLE
Autoupdate version and token string

### PR DESCRIPTION
**Pull request by Randl**
Instead of manually update version and token string each time we can try to acquire them automatically

### CODE REVIEW

**Comment by timakro** [comment]
Works like a charm, awesome!

**Comment by langioletto** [comment]
The link "https://coderus.openrepos.net/whitesoft/whatsapp_scratch" does not work anymore

**Comment by Randl** [comment]
That's unfortunate

**Comment by Wouter0100** [comment]
And it's back online!

**Comment by mgp25** [comment]
I highly dont recommend an auto updater. It is always better to use a fixed version that we know it works. Sometimes new updates has new protocols/security/features that can lead to a block if not handled correctly.

Instead you can create a function apart, that when the user call it, it updates version.

Regards

**Comment by omardlhz** [comment]
I'm still getting "reason":"no_routes" with this using s40, any input?

**Comment by jacargentina** [comment]
I've tried with no luck: still getting old_version. Any advice ?

**Comment by tgalal** [comment]
- Getting the env variables remotely everytime is an extra step that delays connection
- Server will be overloaded with redundant requests
- Remote endpoint might stop working anytime, taking yowsup completely down

Instead, this should perhaps implemented as a new optional env. I imagine it should be something like S40EdgeEnv, AndroidEdgeEnv where there parameters are fetched remotely.

**Comment by edsondario** [comment]
Excelent!

**Pull request closed without merging**
