### PR TITLE
Receive image, document, video, audio

### PR DESCRIPTION
**Pull request by 3dluis**
Add protocolo video and audio
Add decryption document .ENC

### CODE REVIEW

**Comment by ventrixcode** [comment]
Could you try to fix the Upload Issues too?

**Comment by 3dluis** [comment]
You can pass me on an issue open for uploading?

**Comment by dietzi** [comment]
https://github.com/tgalal/yowsup/issues/2149

**Comment by tgalal** [comment]
fixed in v3.2.0

**Pull request closed without merging**
