### PR TITLE
update env_android.py

### PR DESCRIPTION
**Pull request by dlenski**
(from fork: https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py)

I had to apply this in order to successfully create a new Android reigstration with `yowsup-cli registration -E android`.

### CODE REVIEW

**Comment by dlenski** [comment]
@fferraro18, please clarify. While trying to create a new account? Or what?

**Comment by janknobloch** [comment]
Same here: general: Disconnected: Connection Closed
Use android for registration but S40 for using connections:

Thanks @dlenski  this solves registration errors for old android but does not allow connections for me using the cli. 👍

**Comment by rodrigoorrego** [comment]
Hello! I'm new here but already a fan of yowsup! but I'm and also having some issues....

I can request a SMS code with these instructions.. thank you guys for that

but I cannot register... I'm still receiving "old version" error....

any ideas? since now, thanks for the attention! :)

--

yowsup-cli registration --register XXX-XXX --phone 5553XXXXXXXXX --cc 55 -E android
yowsup-cli v2.0.15
yowsup v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"5553XXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5553XXXXXXXX

**Comment by rodrigoorrego** [comment]
if I use -E android i'm getting: old version

if I dont use i'm getting: temporarily unavailable

:(

**Comment by rodrigoorrego** [comment]
anyone has ideas? is yowsup still working?

**Comment by rodrigoorrego** [comment]
weird... it worked in a new cellphone number I've bought here to test

but in the number I was using (and that was registered once before) it just didn't work (always "temporarily unavailable" error)

**Comment by DusanBrejka** [comment]
it looks like this lib isn't working anymore

**Comment by schoerg** [comment]
@DusanBrejka it's still working.

**Pull request merged**
