### PR TITLE
Support for requesting, receiving and setting profile pictures.

### PR DESCRIPTION
**Pull request by ivanbaldo**
I didn't test it very much because of lack of time and also needs a good review and possibly various changes.
I will not be able to test it or work on it until next week so I preferred to create the pull request now in case it is useful as a starting point at least.
If you need me to do more changes before accepting it let me know and I will try my best on monday 29 december.
Thanks!!!

### CODE REVIEW

**Comment by tgalal** [comment]
actually, get, result, and set each should be in a different protocolentity, can you change it? I can change it too but might take a few more days as I'm working on other stuff.

Have a great new year you too :)

**Comment by ivanbaldo** [comment]
Unfortunately, we are looking into https://github.com/mgp25/WhatsAPI-Official since we are primarily PHP developers, we discovered it last week.
I don't know what the final decision will be but my orders currently are to look into it and not do further work on YowSup unless absolutely necessary to maintain our current projects using it, that means no further work in V2, maybe on Legacy if it affects our use case :-(.
Its not final, we may decide that WhatsAPI-Official is not the way to go and continue with YowSup, who knows...
Whatever that decision will be, I really enjoyed helping out a bit, using YowSup (Legacy and a bit of V2) and meeting you, thanks a lot man!!!

**Comment by tgalal** [comment]
Ahh too bad :/ Alright then best of luck! I'll fix the pull request and merge it soon. Would be really great if you got time to help out with yowsup again!

**Comment by ivanbaldo** [comment]
Hello.
It seems you added this changes manually with a few modifications, I made my fork match exactly yours, so you can accept the changes to conserve my history or just close this pull without merging.
Thanks!!!

**Pull request closed without merging**
